### ISSUE TITLE
RavenDB not starting if .NET runtime 5.0.8 is not installed

### ISSUE THREAD

**Issue by RVink** [Augurk/Augurk#494]
Last night the server hosting our Augurk instance installed the latest Windows updates. With that it installed version 5.0.13 of the ASP.NET runtime while also removing any older version. This caused Augurk to not start due to the below exception. 

> fail: Augurk.DocumentStoreProvider[0]
>       Embedded RavenDb server has exited unexpectedly.
> Unhandled exception. System.InvalidOperationException: Unable to start the RavenDB Server
> Error:
> It was not possible to find any compatible framework version
> The framework 'Microsoft.AspNetCore.App', version '5.0.8' was not found.
>   - The following frameworks were found:
>       3.1.22 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>       5.0.13 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> 
> You can resolve the problem by installing the specified framework and/or SDK.
> 
> The specified framework can be found at:
>   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.8&arch=x64&rid=win10-x64
> 
> 
>    at Raven.Embedded.EmbeddedServer.RunServer() in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Embedded\EmbeddedServer.cs:line 299
>    at Raven.Client.Extensions.TaskExtensions.<>c__3`1.<WithCancellation>b__3_0(Task`1 t) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Client\Extensions\TaskExtensions.cs:line 36
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at Raven.Embedded.EmbeddedServer.GetServerUriAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Embedded\EmbeddedServer.cs:line 185
>    at Raven.Embedded.EmbeddedServer.<>c__DisplayClass13_0.<<GetDocumentStoreAsync>b__0>d.MoveNext() in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Embedded\EmbeddedServer.cs:line 143
> --- End of stack trace from previous location ---
>    at Raven.Client.Extensions.TaskExtensions.<>c__3`1.<WithCancellation>b__3_0(Task`1 t) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Client\Extensions\TaskExtensions.cs:line 36
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at Raven.Embedded.EmbeddedServer.GetDocumentStoreAsync(DatabaseOptions options, CancellationToken token) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Embedded\EmbeddedServer.cs:line 161
>    at Augurk.DocumentStoreProvider.StartAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Augurk/DataAccess/DocumentStoreProvider.cs:line 81
>    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
>    at Augurk.Program.Main(String[] args) in /home/vsts/work/1/s/src/Augurk/Program.cs:line 13

Installing version 5.0.8 of the runtime solved the issue.

**Comment by jmezach** [comment]
This is due to the fact that we deploy Augurk as a self-contained application, which includes the .NET Runtime at the time of building. But we also start up an instance of RavenDB as our embedded server and while starting it we pass along the version of the .NET runtime Augurk itself was started with. But RavenDB depends on the machine installed runtime, which in this case didn't match the version of Augurk.

So I guess we'll either have to stop publishing Augurk as a self-contained application and require our users to install a .NET runtime, or we'll need to stop publishing Augurk as an installable all together and focus our attention on running it in containers.

**Comment by RVink** [comment]
The Windows update policy at my company keeps installing the latest .NET runtime as part of a security patch.
We decided to temporarily disable the Augurk publish step in our build pipeline as reinstalling .NET 5.0.8 every day is not a viable solution in the long run. 

It's really appreciated if this can be resolved :).

**Comment by jmezach** [comment]
I guess we could build a non-self contained version of Augurk to resolve this issue, then at least we would use the same runtime for both Augurk and RavenDB.

**Comment by marktaling** [comment]
> I guess we could build a non-self contained version of Augurk to resolve this issue, then at least we would use the same runtime for both Augurk and RavenDB.

I think that would be the best solution for now. At the very least it can be used on the locations where this issue arises. A self-contained container might be preferable in the future, but also poses different demands of the current users.
Perhaps we want to provide both options in the future? Starting with the non-self contained version first now, adding the container with the next feature release?

**Comment by jmezach** [comment]
I've build a non self-contained version of our latest preview and deployed that in our environment and it is working again now. I'll cherry-pick the pipeline change to master so that we'll publish runtime dependent going forward. Unfortunately our master pipeline is currently broken.
