### ISSUE TITLE
RavenDb fails to start when running Augurk in container

### ISSUE THREAD

**Issue by jmezach** [Augurk/Augurk#92]
While trying out Augurk running in a Docker container and describing how to use it I noticed that RavenDb fails to start when it is running inside of a Docker container and the data folder (/app/data) is being volume mapped to the host machine. We'll need to figure out if this is a RavenDb issue, a Docker issue or an Augurk issue.

Stack trace is as follows:

```
System.InvalidOperationException: Unable to start the RavenDB Server
Output:
       _____                       _____  ____
      |  __ \                     |  __ \|  _ \
      | |__) |__ ___   _____ _ __ | |  | | |_) |
      |  _  // _` \ \ / / _ \ '_ \| |  | |  _ <
      | | \ \ (_| |\ V /  __/ | | | |__| | |_) |
      |_|  \_\__,_| \_/ \___|_| |_|_____/|____/


      Safe by default, optimized for efficiency

 Build 41010, Version 4.1, SemVer 4.1.4, Commit dc2e9e3
 PID 35, 64 bits, 4 Cores, Phys Mem 1.952 GBytes, Arch: X64
 Source Code (git repo): https://github.com/ravendb/ravendb
 Built with love by Hibernating Rhinos and awesome contributors!
+---------------------------------------------------------------+


Raven.Client.Exceptions.Server.ServerLoadFailureException: Failed to load system storage
At /app/data/System ---> System.InvalidOperationException: EINVAL when opening /app/data/System/Journals/0000000000000000000.journal
   at Sparrow.Platform.Posix.Syscall.ThrowLastError(Int32 lastError, String msg) in C:\Builds\RavenDB-Stable-4.1\41010\src\Sparrow\Platform\Posix\Syscall.cs:line 350
   at Voron.Platform.Posix.PosixJournalWriter..ctor(StorageEnvironmentOptions options, VoronPathSetting filename, Int64 journalSize) in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\Platform\Posix\PosixJournalWriter.cs:line 61
   at Voron.StorageEnvironmentOptions.DirectoryStorageEnvironmentOptions.<>c__DisplayClass17_0.<CreateJournalWriter>b__1() in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\StorageEnvironmentOptions.cs:line 454
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Voron.StorageEnvironmentOptions.DirectoryStorageEnvironmentOptions.CreateJournalWriter(Int64 journalNumber, Int64 journalSize) in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\StorageEnvironmentOptions.cs:line 462
   at Voron.Impl.Journal.WriteAheadJournal.NextFile(Int32 numberOf4Kbs) in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\Impl\Journal\WriteAheadJournal.cs:line 124
   at Voron.Impl.Journal.WriteAheadJournal.WriteToJournal(LowLevelTransaction tx, String& journalFilePath) in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\Impl\Journal\WriteAheadJournal.cs:line 1371
   at Voron.Impl.LowLevelTransaction.CommitStage2_WriteToJournal() in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\Impl\LowLevelTransaction.cs:line 976
   at Voron.Impl.LowLevelTransaction.Commit() in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\Impl\LowLevelTransaction.cs:line 841
   at Voron.StorageEnvironment.CreateNewDatabase() in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\StorageEnvironment.cs:line 463
   at Voron.StorageEnvironment..ctor(StorageEnvironmentOptions options) in C:\Builds\RavenDB-Stable-4.1\41010\src\Voron\StorageEnvironment.cs:line 152
   at Raven.Server.Storage.Layout.StorageLoader.OpenEnvironmentWithPossibleLayoutUpdate(DirectoryStorageEnvironmentOptions options, StorageEnvironmentType type) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Server\Storage\Layout\StorageLoader.cs:line 40
   at Raven.Server.Storage.Layout.StorageLoader.OpenEnvironment(StorageEnvironmentOptions options, StorageEnvironmentType type) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Server\Storage\Layout\StorageLoader.cs:line 20
   at Raven.Server.ServerWide.ServerStore.Initialize() in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Server\ServerWide\ServerStore.cs:line 566
   --- End of inner exception stack trace ---
   at Raven.Server.ServerWide.ServerStore.Initialize() in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Server\ServerWide\ServerStore.cs:line 570
   at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Server\RavenServer.cs:line 261
   at Raven.Server.Program.Main(String[] args) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Server\Program.cs:line 149


   at Raven.Embedded.EmbeddedServer.<>c__DisplayClass15_0.<<RunServer>b__1>d.MoveNext() in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Embedded\EmbeddedServer.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
   at Raven.Embedded.EmbeddedServer.ReadOutput(StreamReader output, Stopwatch startupDuration, ServerOptions options, Func`3 onLine) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Embedded\EmbeddedServer.cs:line 305
   at Raven.Embedded.EmbeddedServer.RunServer(ServerOptions options) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Embedded\EmbeddedServer.cs:line 225
   at Raven.Embedded.EmbeddedServer.GetServerUriAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Embedded\EmbeddedServer.cs:line 145
   at Raven.Embedded.EmbeddedServer.<>c__DisplayClass11_0.<<GetDocumentStoreAsync>b__0>d.MoveNext() in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Embedded\EmbeddedServer.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at Raven.Embedded.EmbeddedServer.GetDocumentStoreAsync(DatabaseOptions options, CancellationToken token) in C:\Builds\RavenDB-Stable-4.1\41010\src\Raven.Embedded\EmbeddedServer.cs:line 121
   at Raven.Client.Util.AsyncHelpers.RunSync[T](Func`1 task)
   at Augurk.DocumentStoreProvider..ctor(IHostingEnvironment environment, ILogger`1 logger) in /app/Augurk/DataAccess/DocumentStoreProvider.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jmezach** [comment]
Looks like this is a RavenDB issue, since running RavenDB as a Docker container on a Mac doesn't work either, as soon as a Docker volume is being used. I'm afraid there isn't much we can do about this from our end. At least it does work on Windows.
